// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Auction struct {
	ID          string    `json:"id" bson:"_id,omitempty"`
	Host        string    `json:"host"`
	Description string    `json:"description"`
	Offer       float64   `json:"offer"`
	Bids        []*Bid    `json:"bids"`
	Timestamp   time.Time `json:"timestamp"`
	Deadline    time.Time `json:"deadline"`
}

type Bid struct {
	ID        string    `json:"id"`
	Issuer    string    `json:"issuer"`
	Deadline  string    `json:"deadline"`
	Price     float64   `json:"price"`
	Timestamp time.Time `json:"timestamp"`
}

type Chat struct {
	ID       string     `json:"id"`
	Users    []string   `json:"users"`
	Messages []*Message `json:"messages"`
}

type Comment struct {
	ID        string    `json:"id"`
	Author    string    `json:"author"`
	Text      string    `json:"text"`
	LikeCount int       `json:"likeCount"`
	Likes     []string  `json:"likes"`
	Timestamp time.Time `json:"timestamp"`
}

type CommentList struct {
	List  []*Comment `json:"list"`
	Count int        `json:"count"`
}

type Message struct {
	ChatID    string    `json:"chatID"`
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`
	Sender    string    `json:"sender"`
}

type NewUser struct {
	Nickname string `json:"nickname"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Post struct {
	ID          string       `json:"id" bson:"_id,omitempty"`
	Author      string       `json:"author"`
	Description *string      `json:"description"`
	Content     string       `json:"content"`
	Timestamp   time.Time    `json:"timestamp"`
	Comments    *CommentList `json:"comments"`
	LikeCount   int          `json:"likeCount"`
	Likes       []string     `json:"likes"`
}

type User struct {
	Nickname       string   `json:"nickname"`
	Name           string   `json:"name"`
	Email          string   `json:"email"`
	Picture        string   `json:"picture"`
	Followers      []string `json:"followers"`
	FollowersCount int      `json:"followersCount"`
	Following      []string `json:"following"`
}
