// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Nickname string `json:"nickname"`
	Password string `json:"password"`
}

type NewUser struct {
	Nickname string `json:"nickname"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Artist   bool   `json:"artist"`
}

type User struct {
	Nickname string `json:"nickname"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Artist   bool   `json:"artist"`
}
